# Generated by Django 3.1.2 on 2021-10-14 11:18

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogeintrag',
            name='maintext',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
