# Generated by Django 3.2.13 on 2022-05-23 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='pub_date',
            field=models.DateField(null=True, verbose_name='date published'),
        ),
    ]
