# Generated by Django 3.1.2 on 2021-10-14 11:30

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20211014_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogeintrag',
            name='maintext',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
