# Generated by Django 3.2.13 on 2022-05-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_comment_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='captcha',
            field=models.IntegerField(default=0),
        ),
    ]
