# Generated by Django 3.2.9 on 2021-11-13 22:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20211014_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogeintrag',
            name='previewtext',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AlterField(
            model_name='blogeintrag',
            name='sidetext',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
