# Generated by Django 3.2.13 on 2022-05-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_comment_captcha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='captcha',
            field=models.IntegerField(),
        ),
    ]
