# Generated by Django 3.2.9 on 2021-11-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_startseite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogeintrag',
            name='pub_date',
            field=models.DateField(verbose_name='date published'),
        ),
    ]
