# Generated by Django 3.2.13 on 2022-05-26 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_comment_captcha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='sidetext',
        ),
    ]
