# Generated by Django 3.2.13 on 2022-07-19 15:23

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='maintext',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='picture',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
