# Generated by Django 3.2.13 on 2022-06-13 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogpost_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='picture',
            new_name='text_with_pictures',
        ),
    ]
