# Generated by Django 3.2.12 on 2022-02-07 11:25

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20211203_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogeintrag',
            name='sidetext',
            field=ckeditor.fields.RichTextField(max_length=200, null=True),
        ),
    ]
