# Generated by Django 3.2.14 on 2022-07-31 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20220719_1723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ('-votes',)},
        ),
    ]
