# Generated by Django 3.2.13 on 2022-06-13 08:11

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220613_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='maintext',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='text_with_pictures',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=''),
        ),
    ]
