# Generated by Django 3.2.12 on 2022-02-08 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220207_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogeintrag',
            name='view_counter',
            field=models.IntegerField(default=0),
        ),
    ]
